config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
	  get "search_users" => "users#search",as: 'search_users'
    get "search_items" => "items#search", as:'search_items'
    resources :users,             only:[:index, :show, :edit, :update, :destroy] do
    resources :addresses,       only:[:new, :create, :show, :edit, :update, :destroy]
    resources :address_names,   only:[:new, :create ,:show, :edit, :update, :destroy]
    end
    resources :items,           only:[:new, :create, :edit, :update, :destroy, :show, :index] do
    resources :artists,       only:[:edit]
    resources :labels,        only:[:edit]
    resources :genres,        only:[:edit]
    end
    resources :artists,         except:[:edit]
    resources :labels,          except:[:edit]
    resources :genres,          except:[:edit]
    resources :items,           only:[:new, :create, :edit, :update, :destroy]
  	resources :inquiries,       only:[:index, :show]
  	resources :inquiry_replies, only:[:new, :create, :show]
  	resources :orders,          only:[:index, :show, :update]
 	  resources :reviews,         only:[:destroy]
  end

  get "search_users" => "items#search",as: 'search_users'
  get "search_items" => "items#search", as:'search_items'
	resources :users,           only:[:show, :edit, :update, :resign, :destroy]
  resources :items,           only:[:index, :show] do
  resource :likes,           only:[:create, :destroy]
  end
  resources :addresses,       only:[:new, :create, :show, :edit, :update, :destroy]
  resources :address_names,   only:[:new, :create ,:show, :edit, :update, :destroy]
  resources :carts,           only:[:create, :index, :destroy, :update]
  resources :inquiries,       only:[:new, :create]
  resources :orders,          only:[:new, :create, :show, :index]
 	resources :reviews,         only:[:new, :create, :edit, :update]

  get "user/resign" => "users#resign"
  delete "carts" => "carts#destroy"

  root "items#index"
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :authenticate_user!, only: %i[create index destroy]

  def create

  if current_user.carts.any? { |cart| cart.item_id == params[:item_id].to_i }
  	cart = Cart.find_by(item_id: params[:item_id])
  	cart.quantity += 1
  else
  	cart = Cart.new
  	cart.quantity = 1
  end

  cart.item_id = params[:item_id]
  cart.user_id = current_user.id

	cart.save
  redirect_to carts_path
  flash[:add] = "[" + cart.item.name + "]をカートに追加しました"

  end

  def index
  	@carts = current_user.carts
  end

  def update
  	cart = Cart.find_by(item_id: params[:cart][:item_id], user_id: current_user.id)
    if params[:cart][:quantity].to_i <= cart.item.stock
  	  cart.update(quantity: params[:cart][:quantity])
  	  redirect_to carts_path
      flash[:update] = cart.item.name + "の数量を" + params[:cart][:quantity] +"個に変更しました"
    else
      redirect_to carts_path
      flash[:error] = "[" + cart.item.name + "]の在庫数以上はカートに追加できません"
    end
  end

  def destroy
  	cart = Cart.find_by(item_id: params[:cart][:item_id], user_id: current_user.id)
  	cart.destroy
  	redirect_to carts_path
    flash[:remove] = "[" + cart.item.name + "]をカートから削除しました"
  end

  private

  def cart_params
    params.require(:cart).permit(:item_id, :user_id, :quantity)
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/index.html.erb
<div class ="cart-flash" >
	<%= flash[:add] %>
	<%= flash[:update] %>
	<%= flash[:remove] %>
	<%= flash[:error] %>
</div>

	<div class= "cart-title">
	<p>ショッピングカート</p>
	</div>

<% sum_p = 0 %>
<% sum_q = 0 %>
<table class="table-cart-content">
  	<tr class="table-head">
  		<th></th>
  		<th></th>
  		<th></th>
  		<th class="table-stock">在庫数</th>
  		<th class="table-quantity-head">数量</th>
  		<th></th>
  		<th class="table-price-head">価格</th>
  	</tr>
  	<% if @carts.exists? %>
		<% @carts.each do |cart| %>
			<tr class= "table-body">
				<% sum_p += cart.item.price * cart.quantity %>
				<% sum_q += cart.quantity %>

				<td class="table-delete">
					<%= form_for cart, method: :delete do |f| %>
						<%= f.submit "削除", class: 'btn btn-danger' %>
						<%= f.hidden_field :item_id %>
					<% end %>
				</td>
				<%= form_for cart do |f| %>
				<td class="table-image"><%= attachment_image_tag cart.item, :jacket_image,size: '75x75', fallback: "no_images.png" %></td>
				<td class="table-name-artist"> <p class= "item-name"><%= link_to item_path(cart.item_id) do %><%= cart.item.name %> <% end %></p>
						 					   <p><%= cart.item.artist.artist %></p>
				</td>
				<td class="table-stock"><%= cart.item.stock %></td>
				<td class="table-quantity-body"><%= f.text_field :quantity, :size => "3" %></td>
												<%= f.hidden_field :item_id %>
				<td class="reflesh"><%= f.submit "更新", class: 'btn btn-default' %></td>
				<% end %>
				<td class="table-price-body">¥<%= cart.item.price.to_s(:delimited) %></td>
			</tr>
		<% end %>
	<% else %>
		<tr>
			<td class="cart-no-item">カートに商品がありません</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	<% end %>
</table>

<div class="sum">
<h5 class="sum-font"> 小計：（<%= sum_q %>点の商品）¥<%= sum_p.to_s(:delimited) %></h5>
</div>

<div class="button-reg">
<%= link_to "購入へ進む", new_order_path, class: 'btn btn-warning btn-lg' %>
</div>
<div class="button-con">
<%= link_to "お買い物を続ける", items_path, class: 'btn btn-default' %>
</div>