config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
	  get "search_users" => "users#search",as: 'search_users'
    get "search_items" => "items#search", as:'search_items'
    resources :users,             only:[:index, :show, :edit, :update, :destroy] do
    resources :addresses,       only:[:new, :create, :show, :edit, :update, :destroy]
    resources :address_names,   only:[:new, :create ,:show, :edit, :update, :destroy]
    end
    resources :items,           only:[:new, :create, :edit, :update, :destroy, :show, :index] do
    resources :artists,       only:[:edit]
    resources :labels,        only:[:edit]
    resources :genres,        only:[:edit]
    end
    resources :artists,         except:[:edit]
    resources :labels,          except:[:edit]
    resources :genres,          except:[:edit]
    resources :items,           only:[:new, :create, :edit, :update, :destroy]
  	resources :inquiries,       only:[:index, :show]
  	resources :inquiry_replies, only:[:new, :create, :show]
  	resources :orders,          only:[:index, :show, :update]
 	  resources :reviews,         only:[:destroy]
  end

  get "search_users" => "items#search",as: 'search_users'
  get "search_items" => "items#search", as:'search_items'
	resources :users,           only:[:show, :edit, :update, :resign, :destroy]
  resources :items,           only:[:index, :show] do
  resource :likes,           only:[:create, :destroy]
  end
  resources :addresses,       only:[:new, :create, :show, :edit, :update, :destroy]
  resources :address_names,   only:[:new, :create ,:show, :edit, :update, :destroy]
  resources :carts,           only:[:create, :index, :destroy, :update]
  resources :inquiries,       only:[:new, :create]
  resources :orders,          only:[:new, :create, :show, :index]
 	resources :reviews,         only:[:new, :create, :edit, :update]

  get "user/resign" => "users#resign"
  delete "carts" => "carts#destroy"

  root "items#index"
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :discs, 		 dependent: :destroy
  accepts_nested_attributes_for :discs, allow_destroy: true
  has_many :carts, 		 dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :reviews, 	 dependent: :destroy
  has_many :likes, 		 dependent: :destroy

  belongs_to :genre
  belongs_to :label
  belongs_to :artist
  attachment :jacket_image

  validates :name, presence: true
  validates :price, presence: true
  validates :stock, presence: true
  validates :status, presence: true

def self.search(search)
	if search.present?
		Item.joins(:artist).where(['name LIKE? OR artist LIKE?', "%#{search}%","%#{search}%"])
	else
		Item.all
	end
end


def liked_by?(user)
	likes.where(user_id: user.id).exists?
end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy, :show]


  def new
      @item = Item.new
      @disc = @item.discs.build
      @track = @disc.tracks.build
  end

  def show
      @item = Item.find(params[:id])
  end

  def index
      @items = Item.all
      @items = Item.page(params[:page]).reverse_order
  end

  def search
      @items = Item.search(params[:search])
      render :search
  end

  def create
      @item = Item.new(item_params)
      if @item.save
        flash[:notice] = "商品名: " + @item.name + "を追加しました"
        redirect_to admin_items_path
      else
        flash[:notice] = "商品追加に失敗しました"
        redirect_to new_admin_item_path
      end
  end

  def edit
      @item = Item.find(params[:id])
  end

  def update
      @item = Item.find(params[:id])
      if @item.update(item_params)
         flash[:notice] = "商品名: " + @item.name + "を編集しました"
         redirect_to admin_item_path(@item)
      else
         flash[:notice] = "商品編集に失敗しました"
         redirect_to edit_admin_item_path(@item)
      end
  end

  def destroy
      @item = Item.find(params[:id])
      if @item.destroy
         flash[:notice] = "商品名: " + @item.name + "を削除しました"
         redirect_to admin_items_path
      else
        flash[:notice] = "商品削除に失敗しました"
        redirect_to edit_admin_item_path(@item)
      end
  end

  private
  def item_params
      params.require(:item).permit(:name, :disctype, :price, :stock, :status, :jacket_image, :artist_id, :label_id, :genre_id,
      discs_attributes: [:id, :disc_id, :disc_number, :_destroy,
      tracks_attributes: [:id, :track_id, :track_number, :track_name, :_destroy]])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.page(params[:page]).reverse_order
  end

  def search
    @items = Item.search(params[:search])
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to items_path
  end

  def show
    @item = Item.find(params[:id])
  end


private
  def item_params
    params.require(:item).permit(:name, :disctype, :price, :stock, :status, :jacket_image_id, :artist_id, :label_id, :genre_id)
  end


end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/views/items/index.html.erb
<% @items.each do |item| %>
  <div class="item-index-item-box clearfix">
    <%= link_to item_path(item) do %>
      <%= attachment_image_tag item, :jacket_image, class: "item-index-jacket-image", fallback: "no_images.png", size: '200x200' %>
    <% end %>
            <p class="item-index-name"><%= link_to item_path(item) do %>
                <h4><%= item.name %></h4>
               <% end %>
            </p>
            <p><%= item.artist.artist %></p>
            <p class ="item-index-price">¥<%= item.price.to_s(:delimited) %></p>
            <p><%= item.disctype %></p>
            <p><%= item.label.label %></p>
            <p><%= item.status %></p>
            <p><%= item.genre.genre %></p>
  </div>
<% end %>
<%= paginate @items %>

app/views/items/search.html.erb
<div class = 'wrapper'>
  <% result = 0 %>
  <% @items.each do |item| %>
    <% result += 1 %>
  <% end %>

  <h5><%= params[:search] %>：の検索結果</h5>
  <h5><%= result %>件のCDが見つかりました</h5>

　<% @items.each do |item| %>
    <div class="item-index-item-box clearfix">
      <%= link_to item_path(item) do %>
        <%= attachment_image_tag item, :jacket_image, class: "item-index-jacket-image", fallback: "no_images.png", size: '200x200' %>
      <% end %>
      <p class="item-index-name"><%= link_to item_path(item) do %>
        <h4><%= item.name %></h4>
      <% end %>
      </p>
      <p><%= item.artist.artist %></p>
      <p class ="item-index-price">¥<%= item.price.to_s(:delimited) %></p>
      <p><%= item.disctype %></p>
      <p><%= item.label.label %></p>
      <p><%= item.status %></p>
      <p><%= item.genre.genre %></p>
    </div>
  <% end %>
</div>

app/views/items/show.html.erb
<div class = "item-show-jacket-box">
	<div class= "item-show-jacket">
		<%= attachment_image_tag @item, :jacket_image, fallback: "no_images.png", size: '300x300' %>
	</div>
		<% if @item.status == "在庫あり" or @item.stock.to_i == 0 %>
    	<div class = "item-show-jacket"><%= button_to "カートに追加する", carts_path, params: { item_id: @item.id }, class: "btn btn-primary btn-lg" %>
    	</div>
	<% else %>
    	<div class = "item-show-jacket"><button type="button" class="btn btn-default btn-lg" disabled="disabled">カートに追加する</button></div>
	<% end %>

	<div class="item-show-like">
    	<% if user_signed_in? %>
			<% if @item.liked_by?(current_user) %>
				<li>
				  <%= link_to item_likes_path(@item), method: :delete do %>
				  <i class = "fa fa-heart" aria-hidden = "true" style = "color:red;"></i>
				  <%= @item.likes.count %> いいね!
				  <% end %>
				</li>
			<% else %>
				<li>
				  <%= link_to item_likes_path(@item), method: :post do %>
				  <i class = "fa fa-heart" aria-hidden = "true" style = "color:gray;"></i>
				  <%= @item.likes.count %> いいね!
				  <% end %>
				</li>
			<% end %>
		<% else %>
			<br>
			<i class = "fa fa-heart" aria-hidden = "true" style = "color:gray;"></i>
			<%= @item.likes.count %> いいね!
		<% end %>
	</div>
</div>

<div class = "item-show-info">
	<h2><%= @item.name %> </h2>
	<p><%= @item.artist.artist %></p>
	<p class="item-show-price">¥<%= @item.price.to_s(:delimited) %></p>
  <p>CD種別: <%= @item.disctype %></p>
	<p>販売ステータス: <%= @item.status %></p>
	<% if @item.status == "在庫あり" %>
		<p>在庫:  残り<%= @item.stock %></p>
	<% end %>
	<p>ジャンル: <%= @item.genre.genre %></p>
	<p><%= @item.label.label %></p>
</div>

<table class="item-show-track">
	<thead>
		<tr>
			<th>楽曲リスト</th>
		</tr>
	</thead>

	<tbody>
		<% @item.discs.each do |disc| %>
		<tr>
			<td class="item-show-disc-number">ディスク<%= disc.disc_number %> </td>
		</tr>
		<% disc.tracks.each do |track| %>
		<tr>
			<td class="item-show-track-number"><%= track.track_number %>.</td>
			<td class="item-show-track-name"><%= track.track_name %> </td>
		</tr>
		<% end %>
		<% end %>
	</tbody>
</table>