config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords',
    registrations: 'admins/registrations'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :admin do
	  get "search_users" => "users#search",as: 'search_users'
    get "search_items" => "items#search", as:'search_items'
    resources :users,             only:[:index, :show, :edit, :update, :destroy] do
    resources :addresses,       only:[:new, :create, :show, :edit, :update, :destroy]
    resources :address_names,   only:[:new, :create ,:show, :edit, :update, :destroy]
    end
    resources :items,           only:[:new, :create, :edit, :update, :destroy, :show, :index] do
    resources :artists,       only:[:edit]
    resources :labels,        only:[:edit]
    resources :genres,        only:[:edit]
    end
    resources :artists,         except:[:edit]
    resources :labels,          except:[:edit]
    resources :genres,          except:[:edit]
    resources :items,           only:[:new, :create, :edit, :update, :destroy]
  	resources :inquiries,       only:[:index, :show]
  	resources :inquiry_replies, only:[:new, :create, :show]
  	resources :orders,          only:[:index, :show, :update]
 	  resources :reviews,         only:[:destroy]
  end

  get "search_users" => "items#search",as: 'search_users'
  get "search_items" => "items#search", as:'search_items'
	resources :users,           only:[:show, :edit, :update, :resign, :destroy]
  resources :items,           only:[:index, :show] do
  resource :likes,           only:[:create, :destroy]
  end
  resources :addresses,       only:[:new, :create, :show, :edit, :update, :destroy]
  resources :address_names,   only:[:new, :create ,:show, :edit, :update, :destroy]
  resources :carts,           only:[:create, :index, :destroy, :update]
  resources :inquiries,       only:[:new, :create]
  resources :orders,          only:[:new, :create, :show, :index]
 	resources :reviews,         only:[:new, :create, :edit, :update]

  get "user/resign" => "users#resign"
  delete "carts" => "carts#destroy"

  root "items#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :addresses, 		  dependent: :destroy
  has_many :address_names,  dependent: :destroy
  has_many :carts, 		    	dependent: :destroy
  has_many :orders, 		    dependent: :destroy
  has_many :reviews, 		    dependent: :destroy
  has_many :likes, 			    dependent: :destroy

  validates :lastname,       presence: true
  validates :firstname,      presence: true
  validates :lastname_kana,  presence: true
  validates :firstname_kana, presence: true
  validates :postalcode,     presence: true
  validates :address,        presence: true
  validates :phonenumber,    presence: true
  validates :email,          presence: true, uniqueness: true

  default_scope -> { order(lastname_kana: :desc) }

  acts_as_paranoid

  def self.search(search)
    unless search
      return User.all
    else
      return User.where(['lastname LIKE ? OR firstname LIKE ? OR lastname_kana LIKE ? OR firstname_kana LIKE ? OR phonenumber LIKE ? OR email LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_action :authenticate_admin!, only: [:show, :edit, :update, :destroy, :index]

  def show
    @user = User.find(params[:id])
    @addresses = @user.addresses
    @address_names = @user.address_names
  end

  def edit
    @user = User.find(params[:id])
    @addresses = @user.addresses
    @address_names = @user.address_names
    @address = Address.new
    @address_name = AddressName.new
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
     flash[:notice] = "編集しました"
     redirect_to admin_user_path(user)
    else
     address = Address.new
     address_name = AddressName.new
     flash[:notice] = "編集に失敗しました"
     redirect_to edit_admin_user_path(user)
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to admin_user_path(@user)
  end

  def index
    @users = User.all
    @users = User.page(params[:page]).reverse_order
  end

  def search
    @users = User.search(params[:search])
    @users_page = User.page(params[:page]).reverse_order
    render :search
  end

private
  def user_params
    params.require(:user).permit(:lastname, :firstname, :lastname_kana, :firstname_kana, :postalcode, :address, :phonenumber, :email)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: %i[show edit update resign destroy]

  def show
  	@user = User.find(params[:id])
  	@addresses = current_user.addresses
  	@address_names = current_user.address_names
  end

  def edit
    @user = User.find(params[:id])
    @address = Address.new
    @address_name = AddressName.new
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "編集しました"
      redirect_to user_path(current_user)
    else
      @address = Address.new
      @address_name = AddressName.new
      flash[:notice] = "編集に失敗しました"
      redirect_to edit_user_path(current_user)
    end
  end

  def resign
    @user = current_user
  end

  def destroy
    user = current_user
    user.destroy
    redirect_to root_path
  end

private
  def user_params
    params.require(:user).permit(:email, :lastname, :firstname, :lastname_kana, :firstname_kana,
    						                 :phonenumber, :postalcode, :address)
  end

  def correct_user
   	@user = User.find(params[:id])
   	redirect_to user_path(current_user) unless @user == current_user

  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/admin/users/edit.html.erb
<h1>ユーザー情報編集</h1>

  <%= form_for @user, url: admin_user_path(@user) do |f| %>

<table>
  <p> 氏 </p>
    <%= f.text_field :lastname, placeholder:"氏"%><br>

  <p> 名 </p>
    <%= f.text_field :firstname, placeholder:"名"%><br>

  <p> 氏 カナ</p>
    <%= f.text_field :lastname_kana, placeholder:"氏　カナ"%><br>

  <p> 名 カナ</p>
    <%= f.text_field :firstname_kana, placeholder:"名　カナ"%><br>

  <p> 郵便番号</p>
    <%= f.text_field :postalcode, placeholder:"郵便番号"%><br>

  <p> 住所</p>
    <%= f.text_field :address, placeholder:"住所"%><br>

  <p> 電話番号</p>
    <%= f.text_field :phonenumber, placeholder:"電話番号"%><br>

  <p> メールアドレス </p>
    <%= f.text_field :email, placeholder:"メールアドレス"%><br>

</table>

<%= f.submit "編集する" ,class: "btn btn-primary"%>
  <% end %>


  <br>
<p> ----------------------------------</p>
  <br>

    <h2> 宛名を追加する </h2>
      <%= form_for ([:admin, @user, @address_name]) do |f| %>

      <p> 宛名 </p>
        <%= f.text_field :address_name, placeholder:"宛名"%><br>

        <%= f.submit "追加する" ,class: "btn btn-primary" %>

      <% end %>


        <h2> 送付先を追加する </h2>
          <%= form_for ([:admin, @user, @address]) do |f| %>

        <p> 郵便番号 </p>
          <%= f.text_field :postalcode, placeholder:"郵便番号"%><br>

        <p> 住所 </p>
          <%= f.text_area :address, placeholder:"住所"%><br>

          <%= f.submit "追加する", class: "btn btn-primary" %>

<% end %>

app/views/admin/users/index.html.erb
<div class="user-index-title">
  <p>会員一覧</p>
</div>

<div class="user-index-search">
    <%= form_tag(admin_search_users_path,:method => 'get') do %>
      <%= text_field_tag :search, "", size: "40" , placeholder: "ユーザー名/電話番号/メールアドレス" %>
      <%= submit_tag '検索', :lastname => nil, class:"btn btn-default" %>
    <% end %>
</div>



<table border="1", class="user-index-table">
  <thead>
    <tr>
       <th>ユーザー名</th>
       <th>ユーザー名（カナ）</th>
       <th>電話番号</th>
       <th>メールアドレス</th>
       <th></th>
    </tr>
  </thead>
  <% @users.each do |user| %>
    <tbody>
      <tr>
         <td> <%= user.lastname %><%= user.firstname %></td>
         <td> <%= user.lastname_kana %><%= user.firstname_kana %></td>
         <td> <%= user.phonenumber %></td>
         <td> <%= user.email %></td>
         <td class="user-index-detail"> <%= link_to "ユーザー詳細", admin_user_path(user), class:"btn btn-primary" %>
         </td>
      </tr>
    </tbody>
  <% end %>
</table>


<%= paginate @users %>

app/views/admin/users/search.html.erb
<div class="user-index-title">
  <p>会員一覧:検索結果</p>
</div>

<div class="user-index-search">
    <%= form_tag(admin_search_users_path,:method => 'get') do %>
      <%= text_field_tag :search, "", size: "40" %>
      <%= submit_tag '検索', :lastname => nil, class:"btn btn-default" %>
    <% end %>
</div>




 <% @users.each do |user| %>

<table border="5", class="user-index-table">
<thead>
  <tr>
     <th>ユーザー名</th>
     <th>ユーザー名（カナ）</th>
     <th>電話番号</th>
     <th>メールアドレス</th>
  </tr>
</thead>

<tbody>
  <tr>
     <td> <%= user.lastname %><%= user.firstname %></td>
     <td> <%= user.lastname_kana %><%= user.firstname_kana %></td>
     <td> <%= user.phonenumber %></td>
     <td> <%= user.email %></td>
  </tr>
</tbody>
</table>
<p class="user-index-detail">  <%= link_to "ユーザー詳細", admin_user_path(user), class:"btn btn-primary" %></p>



<% end %>

<%= paginate @users_page %>

app/views/admin/users/show.html.erb
<h1 class="fas fa-user">会員詳細</h1>


<h3>ユーザー情報</h3>
<table>
  <tr>
    <td>名前</td>
    <td><%= @user.lastname %>  <%= @user.firstname %></td>
  </tr>
  <tr>
    <td>名前(カナ)</td>
    <td><%= @user.lastname_kana %>  <%= @user.firstname_kana %></td>
  </tr>
  <tr>
    <td>郵便番号</td>
    <td><%= @user.postalcode %></td>
  </tr>
  <tr>
    <td>住所</td>
    <td><%= @user.address %></td>
  </tr>
  <tr>
    <td>メールアドレス</td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td>電話番号</td>
    <td><%= @user.phonenumber %></td>
  </tr>
</table>

<h3>宛名一覧</h3>
<table>
  <% @address_names.each do |address_name| %>
    <tr>
      <td class="mypage-address-name"><%= address_name.address_name %></td>
      <td><%= link_to "編集", edit_admin_user_address_name_path(@user, address_name), class:"btn btn-primary" %></td>
      <td><%= link_to "削除", admin_user_address_name_path(@user, address_name), method: :delete, class:"btn btn-danger" %>
      </td>
    </tr>
  <% end %>
</table>

<h3>送付先一覧</h3>
<table>
  <% @addresses.each do |address| %>
    <tr>
      <th>郵便番号</th>
      <th class="mypage-address">住所</th>
      <th></th>
      <th></th>
    </tr>
    <tr>
      <td><%= address.postalcode %></td>
      <td><%= address.address %></td>
      <td><%= link_to "編集", edit_admin_user_address_path(@user, address), class:"btn btn-primary" %></td>
      <td><%= link_to "削除", admin_user_address_path(@user, address), method: :delete , class:"btn btn-danger"%></td>
    </tr>
  <% end %>
</table>

    <br>
  <br>
<p> <%= link_to"プロフィール編集　宛名・送付先追加", edit_admin_user_path(@user), class: 'btn btn-primary' %> </p>